name: Build PDF Layout Translator (Single EXE)

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  APP_NAME: 'PDF-Layout-Translator'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Build single EXE with PyInstaller
      run: |
        echo "🔨 Building the executable with the correct source path..."
        pyinstaller --noconfirm --onefile --windowed --name "${{ env.APP_NAME }}" `
        --paths src `
        --hidden-import=reportlab `
        --hidden-import=PIL `
        --hidden-import=fitz `
        --hidden-import=lxml `
        --hidden-import=fontTools `
        --hidden-import=googletrans `
        src/main.py

    - name: Verify EXE creation
      run: |
        if (Test-Path "dist/${{ env.APP_NAME }}.exe") {
          Write-Host "✅ EXE created successfully!"
        } else {
          Write-Host "❌ EXE creation failed."
          exit 1
        }

    - name: Upload EXE as an Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}
        path: dist/${{ env.APP_NAME }}.exe
        retention-days: 7

    - name: Create Release and Upload EXE
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/${{ env.APP_NAME }}.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
