name: Build PDF Layout Translator (Single EXE)

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  APP_NAME: 'PDF-Layout-Translator'

jobs:
  build-and-test:
    name: Test, Build & Release
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Installe les dépendances de production ET de développement
        pip install -e .[dev]
    
    - name: Run linter (Flake8)
      run: |
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Build single EXE with PyInstaller
      run: |
        echo "🔨 Building the executable..."
        pyinstaller --noconfirm --onefile --windowed --name "${{ env.APP_NAME }}" src/main.py
    
    - name: Verify EXE creation
      run: |
        if (Test-Path "dist/${{ env.APP_NAME }}.exe") {
          Write-Host "✅ EXE created successfully!"
        } else {
          Write-Host "❌ EXE creation failed."
          exit 1
        }

    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/${{ env.APP_NAME }}.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
