name: Build PDF Layout Translator (Single EXE)

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  APP_NAME: 'PDF-Layout-Translator'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Installs production and development dependencies from setup.py
        pip install -e .[dev]
    
    - name: Build single EXE with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --name "${{ env.APP_NAME }}" src/main.py

    # --- THIS IS THE CRUCIAL STEP I MISSED ---
    # This part saves the EXE as an Artifact for EVERY build (pushes, PRs, etc.)
    - name: Upload EXE as an Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }} # The name of the downloadable zip
        path: dist/${{ env.APP_NAME }}.exe # The path to the file to upload
        retention-days: 7 # Keep the artifact for 7 days

    # This part ONLY runs if you push a tag (e.g., git tag v2.0.3; git push origin v2.0.3)
    - name: Create Release and Upload EXE
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/${{ env.APP_NAME }}.exe # The file to attach to the release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
